const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.SVGPicture,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Mouse: 0},
	{Teclado: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{personagem: 0},
	{saúde: 0},
	{Projétil: 0},
	{monstro: 0},
	{DestruirForaDoLayout: 0},
	{bala: 0},
	{Esmaecer: 0},
	{explosão: 0},
	{TEXTO: 0},
	{SCORE: 0},
	{Texto2: 0},
	{Botão: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{ImagemSVG: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{monstro2: 0},
	{monstro3: 0},
	{monstro4: 0},
	{monstro5: 0},
	{monstro6: 0},
	{monstro7: 0},
	{Score: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	personagem: class extends self.ISpriteInstance {},
	monstro: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	explosão: class extends self.ISpriteInstance {},
	TEXTO: class extends self.ITextInstance {},
	SCORE: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	ImagemSVG: class extends self.ISVGPictureInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	monstro2: class extends self.ISpriteInstance {},
	monstro3: class extends self.ISpriteInstance {},
	monstro4: class extends self.ISpriteInstance {},
	monstro5: class extends self.ISpriteInstance {},
	monstro6: class extends self.ISpriteInstance {},
	monstro7: class extends self.ISpriteInstance {}
}